WebUI/Controllers/AdminController.cs
using Business.Abstract;
using Entity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class AdminController : Controller
    {


        // product
        private IProductService _productService;
        private ICategoryService _categoryService;
        public AdminController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public IActionResult ProductList()
        {

            return View(new ProductListModel()
            {
                Products = _productService.GetAll()
            });
        }

        [HttpGet]
        public IActionResult CreateProduct()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateProduct(ProductModel model)
        {
            var entity = new Product()
            {
                Name = model.Name,
                Price = model.Price,
                Description = model.Description,
                ImageUrl = model.ImageUrl
            };
            _productService.Create(entity);
            return RedirectToAction("ProductList");
        }


        public IActionResult EditProduct(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = _productService.GetById((int)id);
            if (entity == null)
            {
                return NotFound();
            }

            var model = new ProductModel()
            {
                Id = entity.Id,
                Name = entity.Name,
                Price = entity.Price,
                Description = entity.Description,
                ImageUrl = entity.ImageUrl
            };
            return View(model);
        }



        [HttpPost]
        public IActionResult EditProduct(ProductModel model)
        {
            var entity = _productService.GetById(model.Id);
            if (entity != null)
            {
                return NotFound();
            }
            entity.Name = model.Name;
            entity.Description = model.Description;
            entity.Price = model.Price;
            entity.ImageUrl = model.ImageUrl;

            _productService.Update(entity);
            return RedirectToAction("ProductList");
        }

        [HttpPost]
        public IActionResult DeleteProduct(int productId)
        {
            var entity = _productService.GetById(productId);
            if (entity != null)
            {
                _productService.Delete(entity);
            }
            return RedirectToAction("ProductList");
        }


        // category

        public IActionResult CategoryList()
        {
            return View(new CategoryListModel()
            {
                Categories = _categoryService.GetAll()
            });
        }

        [HttpGet]
        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateCategory(CategoryModel model)
        {
            var entity = new Category()
            {
                Name = model.Name
            };
            _categoryService.Create(entity);
            return RedirectToAction("CategoryList");
        }


        [HttpGet]
        public IActionResult EditCategory(int id)
        {


            var entity = _categoryService.GetByIdWithProducts(id);

            return View(new CategoryModel()
            {
                Id = entity.Id,
                Name = entity.Name,
                Products=entity.ProductCategories.Select(p=>p.Product).ToList()
            });
        }
        [HttpPost]
        public IActionResult EditCategory(CategoryModel model)
        {


            var entity = _categoryService.GetByIdWithProducts(model.Id);
            if (entity == null)
            {
                return NotFound();
            }
            entity.Name = model.Name;
            _categoryService.Update(entity);
            return RedirectToAction("CategoryList");
        }

        [HttpPost]
        public IActionResult DeleteCategory(int categoryId)
        {
            var entity = _categoryService.GetById(categoryId);
            if (entity != null)
            {
                _categoryService.Delete(entity);
            }
            return RedirectToAction("CategoryList");
        }

    }
}

WebUI/Controllers/ShopController.cs
using Business.Abstract;
using Entity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class ShopController : Controller
    {
        IProductService _productService;

        public ShopController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Details(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails((int)id);
            if (product==null)
            {
                return NotFound();
            }
            return View(new ProductDetailsModel()
            {
                Product = product,
                Categories=product.ProductCategories.Select(i=>i.Category).ToList()
            });
        }

        public IActionResult List(string category , int page=1)
        {
            const int pageSize = 3;
            return View(new ProductListModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems=_productService.GetCountByCategory(category),
                    CurrentPage =page,
                    ItemsPerPage=pageSize,
                    CurrentCategory=category
                },
                Products = _productService.GetProductsByCategory(category,page,pageSize)
            });
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link  rel="stylesheet" href="~/lib/font-awesome/css/all.min.css"/>
</head>
<body>

    <partial name="_navbar">
        
        
        
        <div class="container pt-100 mb-5">
            @RenderBody()
        
            </div>

     @await Html.PartialAsync("_footer")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    @RenderSection("Scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_footer.cshtml
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ShopApp Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Aliyasin Göktürk</a>
        </div>
    </footer>

WebUI/Views/Shared/_navbar.cshtml
<header>
        <nav class="nav navbar-expand-lg navbar-dark text-white bg-success fixed-top">

            <div class="container">
                <a class="navbar-brand" href="/">ShopApp</a>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item" ><a class="nav-link active" href="/Home/Index"> Home</a></li>
                    <li class="nav-item"><a class="nav-link " asp-controller="Shop" asp-action="List"> Products</a></li>
                    <li class="nav-item"><a class="nav-link " href="#">Cart </a></li>
                    <li class="nav-item"><a class="nav-link " href="#"> Orders</a></li>
                    <li class="nav-item"><a asp-controller="Admin" asp-action="CreateProduct" class="nav-link "> Add Product</a></li>
                    <li class="nav-item"><a class="nav-link " href="/admin/ProductList"> Admin Product</a></li>
                    <li class="nav-item"><a class="nav-link "  asp-controller="Admin" asp-action="CreateCategory"> Add Category</a></li>
                    <li class="nav-item"><a class="nav-link "  asp-controller="Admin" asp-action="CategoryList"> Admin Category</a></li>
                    <li class="nav-item"><a class="nav-link "  asp-controller="Admin" asp-action="CreateProduct"> Logout</a></li>
                    <li class="nav-item"><a class="nav-link "  asp-controller="Admin" asp-action="CreateProduct"> Login</a></li>
                    <li class="nav-item"><a class="nav-link "  asp-controller="Admin" asp-action="CreateProduct"> Register</a></li>
             
                </ul>
            </div>
        </nav>
    </header>

WebUI/Views/Shared/_product.cshtml
@model Product

<div class="col-md-4">
    <div class="card mb-3">
        <img src="~/img/@Model.ImageUrl" alt="@Model.Name" />
        <div class="card-body">
            <h4 class="card-title">
                <a href="#">@Model.Name</a>
            </h4>
            <small class="text-muted"><i class="fa-solid fa-turkish-lira-sign"></i>@Model.Price</small>
        </div>
        <div class="card-footer text-center">
            <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-outline-primary btn-sm ">Details</a>
            <a href="#" class="btn btn-outline-primary btn-sm ml-3">Add To Cart</a>
        </div>
    </div>
</div>

WebUI/Views/Shared/_slider.cshtml
<div id="mySlider" class="carousel slide mb-3" data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#mySlider" data-slider-to="0" class="active"></li>
        <li data-target="#mySlider" data-slider-to="1" ></li>
        <li data-target="#mySlider" data-slider-to="2" ></li>
    </ol>


    <div class="carousel-inner">
        <div class="carousel-item active">
            <img  src="~/img/slider1.png" class="d-block img-fluid"/>
        </div>
        <div class="carousel-item ">
            <img  src="~/img/slider2.png" class="d-block img-fluid"/>
        </div>
        <div class="carousel-item ">
            <img  src="~/img/slider3.png" class="d-block img-fluid"/>
        </div>
    </div>

    <a href="#mySlider"  data-slide="prev" class="carousel-control-prev"><span class="carousel-control-prev-icon"></span></a>
    <a href="#mySlider"  data-slide="next" class="carousel-control-next"><span class="carousel-control-next-icon"></span></a>

</div>